### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
There are several small changes. Functionality is not affected.

To make it understandable, I split it up into several commits.

### CODE REVIEW

**Comment by deg0nz** [comment]
Hi @KristjanESPERANTO,
thank you for this PR! 

I Have just some minor questions. Please see below.

**Review by deg0nz — COMMENTED** [review]
You said, that this is not working with the `hafas-client`. 
Why won't this work? Is the `stationId` different somehow?

(I don't use this feature and it was implemented a long time ago, that's why I'm asking... Maybe something has changed)

Edit: Meh, I thought this comment will be pinned to the commit. This is about 77d6b87, of course

**Comment by deg0nz** [comment]
Also, I assume, you have used some kind of linting config..?

If yes, could you please add your prettier/jslint/... config to this repo, so we can easily keep the style on future commits? [That would be great.](http://www.quickmeme.com/img/46/46b35216e5fc5bc36b9b718384ee8f0b80311fc74feda5fb1b850a1b977bbf49.jpg) 😬

**Comment by KristjanESPERANTO** [comment]
> You said, that this is not working with the `hafas-client`. Why won't this work?

The README says: _`vbb-hafas` returns departures from several train stations in the area of the main train station._<br> Since `hafas-client` is now used instead of `vbb-hafas` and `hafas-client` does not have this behavior, `ignoredStations` has no effect.

>  Is the `stationId` different somehow?

It seems so. In the example of the README is/was a non-working stationID.

> Also, I assume, you have used some kind of linting config..?

This is still a semi-manual process with my IDE, I am still a bit dissatisfied with the results of automatic linting. But I definitely want to introduce it for my modules and am currently working on it.

**Comment by KristjanESPERANTO** [comment]
Sorry, it wasn't on purpose to already add the `dependabot.yml`. But from my point of view it can stay there.

**Comment by deg0nz** [comment]
Thanks for your contribution! Very mich appreciated :)

**Pull request merged**
