### PR TITLE
Upgrade hafas-client to v6 + some rework

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
It works fine for me. Since it's a major change, it would be good if it was tested on other machines as well.

### CODE REVIEW

**Comment by deg0nz** [comment]
I just checked. I need some time to look over it.
I currently have no MM installed here, because I moved. So please bare with me :)

**Comment by rejas** [comment]
A quick check with my config worked too. Not much time to make a code review though (👶)...

**Comment by KristjanESPERANTO** [comment]
Sorry, I should have kept the PR smaller.

**Comment by rejas** [comment]
> Sorry, I should have kept the PR smaller.

So, maybe cut some easy parts (like typos, documentation updates) into seperate PRs (that we can merge faster) so that the v6 stuff is easier to check?

**Comment by KristjanESPERANTO** [comment]
I've moved most of the changes irrelevant to the hafas-client upgrade to PR #161 :slightly_smiling_face: 

When #161 is done, I'll adjust this PR.

**Comment by KristjanESPERANTO** [comment]
There are still a lot of changes, but at least it should be a bit more manageable now than before.

**Pull request merged**
