### PR TITLE
fixed display error of express lines

### PR DESCRIPTION
**Pull request by fry0815**
This is the PR to fix the issue #5 
ice
Now it looks like this. The textcolor is not nice, but it is the original color of the ICE logo :P

### CODE REVIEW

**Comment by deg0nz** [comment]
@fry0815 thanks for your work!

hm.. but honestly I really don't like that color. What if we just show "IC/ICE" without a backgroud color and display it as cursive font?
Or we convert [this logo](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/ICE-Logo.svg/2000px-ICE-Logo.svg.png) to an svg and display this instead...

And I haven't looked into vbb-hafas data for a while now. Doesn't it make a difference between IC and ICE?

**Comment by fry0815** [comment]
@deg0nz yeah you are right, the color is not nice, it comes from the vbb-hafas data.

And no, there isn't a difference between IC and ICE. The EC is also showing as IC/ICE -.-

I try to change the style. You can open a request change ;)

**Comment by deg0nz** [comment]
I think you can just push the changes to your fork's master branch. The changes will automatically appear here

**Comment by deg0nz** [comment]
Hey, @fry0815!
Any news on this one?

**Comment by fry0815** [comment]
@deg0nz no sry, atm i have not so much time :/
i try to do that in the next days.

**Comment by deg0nz** [comment]
@fry0815 Could you please update your branch from my master branch so I can merge your PR?

**Comment by fry0815** [comment]
image
New Version, is this better?

**Comment by deg0nz** [comment]
Yeah, this looks nice!

**Comment by deg0nz** [comment]
Ok, if you say you don't want to make any changes, I'm going to merge this. Looks fine for me though.

**Comment by fry0815** [comment]
I'm done, you can merge it :)

Thank you

**Pull request merged**
