### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by rejas**

### CODE REVIEW

**Comment by deg0nz** [comment]
Hey, @rejas! Thanks for your work in this PR!

One thing about  commit 767daeab80c4ecda38b9ec750659f93513eacbd7: 
I use the `new Promise` direction in the `getFirstReachableDeparturePosition`-function in [line 315](https://github.com/deg0nz/MMM-PublicTransportBerlin/blob/9db0387fc106c4bbc5db8fbfd15ef5cdf9f9cb92/MMM-PublicTransportBerlin.js#L315) of `MMM-PublicTransportBerlin.js`.

Although [node.green](http://node.green/#ES2015-built-ins-Promise-basic-functionality) says, that basic Promise functionality is working with node >= 6.4.0 I'm not quite shure, that this is going to work, since I only used it with BluebirdJS before.

Are you sure, this will work with vanilla NodeJS?

**Comment by deg0nz** [comment]
Hmm.. OK I looked it up, it seems that it should work...

**Comment by rejas** [comment]
Worked for me on my Raspberry PI, with node v6.11.0 (which should be the standard version there I assume).

**Comment by deg0nz** [comment]
OK, gonna merge this now..

**Pull request merged**
